services:
  mysql8:
    image: mysql:8.0.44
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - "13316:3306"

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis/data:/data
    ports:
      - "16379:6379"

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.2
    ports:
    - 18080:8080
    - 50051:50051
    volumes:
    - ./data/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
