[project]
name = "llmops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aerich>=0.9.2",
    "aiomysql>=0.3.2",
    "aioredis>=2.0.1",
    "celery>=5.6.2",
    "cos-python-sdk-v5>=1.9.41",
    "cryptography>=46.0.3",
    "fastapi>=0.124.2",
    "injector>=0.23.0",
    "jieba>=0.42.1",
    "langchain>=1.1.3",
    "langchain-community>=0.4.1",
    "langchain-deepseek>=1.0.1",
    "langchain-huggingface>=1.2.0",
    "langchain-openai>=1.1.3",
    "langchain-weaviate>=0.0.6",
    "langgraph>=1.0.5",
    "marshmallow>=3.26.1",
    "openai>=2.11.0",
    "openapi>=2.0.0",
    "pydantic[email]>=2.12.5",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "redis[asyncio]>=7.1.0",
    "sentence-transformers>=5.2.0",
    "tiktoken>=0.12.0",
    "tortoise-orm>=0.25.1",
    "unstructured[docx,pdf]>=0.18.27",
    "uvicorn>=0.38.0",
    "watchfiles>=1.1.1",
    "weaviate-client>=4.19.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.aerich]
tortoise_orm = "config.config.DB_CONFIG"
location = "./migrations"
src_folder = "./."
